export const qqFaceList = [
  { id: 0, text: '/惊讶', hasImage: true, format: 'gif' },
  { id: 1, text: '/撇嘴', hasImage: true, format: 'gif' },
  { id: 2, text: '/色', hasImage: true, format: 'gif' },
  { id: 3, text: '/发呆', hasImage: true, format: 'gif' },
  { id: 4, text: '/得意', hasImage: true, format: 'gif' },
  { id: 5, text: '/流泪', hasImage: true, format: 'gif', stickerId: '16', stickerType: 1 },
  { id: 6, text: '/害羞', hasImage: true, format: 'gif' },
  { id: 7, text: '/闭嘴', hasImage: true, format: 'gif' },
  { id: 8, text: '/睡', hasImage: true, format: 'gif' },
  { id: 9, text: '/大哭', hasImage: true, format: 'gif' },
  { id: 10, text: '/尴尬', hasImage: true, format: 'gif' },
  { id: 11, text: '/发怒', hasImage: true, format: 'gif' },
  { id: 12, text: '/调皮', hasImage: true, format: 'gif' },
  { id: 13, text: '/呲牙', hasImage: true, format: 'gif' },
  { id: 14, text: '/微笑', hasImage: true, format: 'gif' },
  { id: 15, text: '/难过', hasImage: true, format: 'gif' },
  { id: 16, text: '/酷', hasImage: true, format: 'gif' },
  { id: 18, text: '/抓狂', hasImage: true, format: 'gif' },
  { id: 19, text: '/吐', hasImage: true, format: 'gif' },
  { id: 20, text: '/偷笑', hasImage: true, format: 'gif' },
  { id: 21, text: '/可爱', hasImage: true, format: 'gif' },
  { id: 22, text: '/白眼', hasImage: true, format: 'gif' },
  { id: 23, text: '/傲慢', hasImage: true, format: 'gif' },
  { id: 24, text: '/饥饿', hasImage: true, format: 'gif' },
  { id: 25, text: '/困', hasImage: true, format: 'gif' },
  { id: 26, text: '/惊恐', hasImage: true, format: 'gif' },
  { id: 27, text: '/流汗', hasImage: true, format: 'gif' },
  { id: 28, text: '/憨笑', hasImage: true, format: 'gif' },
  { id: 29, text: '/悠闲', hasImage: true, format: 'gif' },
  { id: 30, text: '/奋斗', hasImage: true, format: 'gif' },
  { id: 31, text: '/咒骂', hasImage: true, format: 'gif' },
  { id: 32, text: '/疑问', hasImage: true, format: 'gif' },
  { id: 33, text: '/嘘', hasImage: true, format: 'gif' },
  { id: 34, text: '/晕', hasImage: true, format: 'gif' },
  { id: 35, text: '/折磨', hasImage: true, format: 'gif' },
  { id: 36, text: '/衰', hasImage: true, format: 'gif' },
  { id: 37, text: '/骷髅', hasImage: true, format: 'gif' },
  { id: 38, text: '/敲打', hasImage: true, format: 'gif' },
  { id: 39, text: '/再见', hasImage: true, format: 'gif' },
  // { id: 41, text: '/发抖', hasImage:true, format: 'gif' },
  { id: 42, text: '/爱情', hasImage: true, format: 'gif' },
  { id: 43, text: '/跳跳', hasImage: true, format: 'gif' },
  { id: 46, text: '/猪头', hasImage: true, format: 'gif' },
  { id: 49, text: '/拥抱', hasImage: true, format: 'gif' },
  { id: 53, text: '/蛋糕', hasImage: true, format: 'gif', stickerId: '17', stickerType: 1 },
  { id: 54, text: '/__闪电', hasImage: true, format: 'gif' },
  { id: 55, text: '/炸弹', hasImage: true, format: 'gif' },
  { id: 56, text: '/刀', hasImage: true, format: 'png' },
  { id: 57, text: '/__足球', hasImage: true, format: 'gif' },
  { id: 59, text: '/便便', hasImage: true, format: 'gif' },
  { id: 60, text: '/咖啡', hasImage: true, format: 'gif' },
  { id: 61, text: '/__吃饭', hasImage: true, format: 'gif' },
  { id: 63, text: '/玫瑰', hasImage: true, format: 'gif' },
  { id: 64, text: '/凋谢', hasImage: true, format: 'gif' },
  { id: 66, text: '/爱心', hasImage: true, format: 'gif' },
  { id: 67, text: '/心碎', hasImage: true, format: 'gif' },
  { id: 69, text: '/__礼物', hasImage: true, format: 'gif' },
  { id: 74, text: '/太阳', hasImage: true, format: 'gif', stickerId: '35', stickerType: 1 },
  { id: 75, text: '/月亮', hasImage: true, format: 'gif', stickerId: '36', stickerType: 1 },
  { id: 76, text: '/赞', hasImage: true, format: 'gif' },
  { id: 77, text: '/踩', hasImage: true, format: 'gif' },
  { id: 78, text: '/握手', hasImage: true, format: 'gif' },
  { id: 79, text: '/胜利', hasImage: true, format: 'gif' },
  // { id: 85, text: '/飞吻', hasImage:true, format: 'gif' },
  { id: 86, text: '/怄火', hasImage: true, format: 'gif' },
  { id: 89, text: '/西瓜', hasImage: true, format: 'gif' },
  { id: 96, text: '/冷汗', hasImage: true, format: 'gif' },
  { id: 97, text: '/擦汗', hasImage: true, format: 'gif' },
  { id: 98, text: '/抠鼻', hasImage: true, format: 'gif' },
  { id: 99, text: '/鼓掌', hasImage: true, format: 'gif' },
  { id: 100, text: '/糗大了', hasImage: true, format: 'gif' },
  { id: 101, text: '/坏笑', hasImage: true, format: 'gif' },
  { id: 102, text: '/左哼哼', hasImage: true, format: 'gif' },
  { id: 103, text: '/右哼哼', hasImage: true, format: 'gif' },
  { id: 104, text: '/哈欠', hasImage: true, format: 'gif' },
  { id: 105, text: '/鄙视', hasImage: true, format: 'gif' },
  { id: 106, text: '/委屈', hasImage: true, format: 'gif' },
  { id: 107, text: '/快哭了', hasImage: true, format: 'gif' },
  { id: 108, text: '/阴险', hasImage: true, format: 'gif' },
  { id: 109, text: '/左亲亲', hasImage: true, format: 'gif' },
  { id: 110, text: '/吓', hasImage: true, format: 'gif' },
  { id: 111, text: '/可怜', hasImage: true, format: 'gif' },
  { id: 112, text: '/菜刀', hasImage: true, format: 'png' },
  { id: 113, text: '/__啤酒', hasImage: true, format: 'gif' },
  { id: 114, text: '/篮球', hasImage: true, format: 'gif', stickerId: '13', stickerType: 2 },
  { id: 115, text: '/__乒乓球', hasImage: true, format: 'gif' },
  { id: 116, text: '/示爱', hasImage: true, format: 'gif' },
  { id: 117, text: '/__七星瓢虫', hasImage: true, format: 'gif' },
  { id: 118, text: '/抱拳', hasImage: true, format: 'gif' },
  { id: 119, text: '/勾引', hasImage: true, format: 'gif' },
  { id: 120, text: '/拳头', hasImage: true, format: 'gif' },
  { id: 121, text: '/差劲', hasImage: true, format: 'gif' },
  { id: 122, text: '/爱你', hasImage: true, format: 'gif' },
  { id: 123, text: '/NO', hasImage: true, format: 'gif' },
  { id: 124, text: '/OK', hasImage: true, format: 'gif' },
  { id: 125, text: '/转圈', hasImage: true, format: 'gif' },
  { id: 126, text: '/__企鹅鞠躬', hasImage: true, format: 'gif' },
  { id: 127, text: '/__企鹅回头', hasImage: true, format: 'gif' },
  { id: 128, text: '/__企鹅跳绳', hasImage: true, format: 'gif' },
  { id: 129, text: '/挥手', hasImage: true, format: 'gif' },
  { id: 130, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 131, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 132, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 133, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 134, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 135, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 136, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 137, text: '/鞭炮', hasImage: true, format: 'gif', stickerId: '18', stickerType: 1 },
  { id: 138, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 140, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 144, text: '/喝彩', hasImage: true, format: 'gif' },
  { id: 146, text: '/爆筋', hasImage: true, format: 'gif' },
  { id: 147, text: '/棒棒糖', hasImage: true, format: 'gif' },
  { id: 148, text: '/喝奶', hasImage: true, format: 'gif' },
  { id: 151, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 158, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 168, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 169, text: '/手枪', hasImage: true, format: 'gif' },
  { id: 171, text: '/茶', hasImage: true, format: 'gif' },
  { id: 172, text: '/眨眼睛', hasImage: true, format: 'gif' },
  { id: 173, text: '/泪奔', hasImage: true, format: 'gif' },
  { id: 174, text: '/无奈', hasImage: true, format: 'gif' },
  { id: 175, text: '/卖萌', hasImage: true, format: 'gif' },
  { id: 176, text: '/小纠结', hasImage: true, format: 'gif' },
  { id: 177, text: '/喷血', hasImage: true, format: 'gif' },
  { id: 178, text: '/斜眼笑', hasImage: true, format: 'gif' },
  { id: 179, text: '/doge', hasImage: true, format: 'gif' },
  { id: 180, text: '/惊喜', hasImage: true, format: 'gif' },
  { id: 181, text: '/戳一戳', hasImage: true, format: 'gif', stickerId: '37', stickerType: 1 },
  { id: 182, text: '/笑哭', hasImage: true, format: 'gif' },
  { id: 183, text: '/我最美', hasImage: true, format: 'gif' },
  { id: 185, text: '/羊驼', hasImage: true, format: 'gif' },
  { id: 186, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 187, text: '/幽灵', hasImage: true, format: 'gif' },
  { id: 188, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 189, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 190, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 191, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 192, text: '/xxx', hasImage: true, format: 'gif' },
  // { id: 193, text:  hasImage:true,'/大笑', format: 'gif' },
  { id: 194, text: '/不开心', hasImage: true, format: 'gif' },
  { id: 195, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 196, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 197, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 198, text: '/呃', hasImage: true, format: 'gif' },
  { id: 199, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 200, text: '/求求', hasImage: true, format: 'gif' },
  { id: 201, text: '/点赞', hasImage: true, format: 'gif' },
  { id: 202, text: '/无聊', hasImage: true, format: 'gif' },
  { id: 203, text: '/托脸', hasImage: true, format: 'gif' },
  { id: 204, text: '/吃', hasImage: true, format: 'gif' },
  { id: 205, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 206, text: '/害怕', hasImage: true, format: 'gif' },
  { id: 207, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 208, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 209, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 210, text: '/飙泪', hasImage: true, format: 'gif' },
  { id: 211, text: '/我不看', hasImage: true, format: 'gif' },
  { id: 212, text: '/托腮', hasImage: true, format: 'gif' },
  { id: 214, text: '/啵啵', hasImage: true, format: 'gif' },
  { id: 215, text: '/糊脸', hasImage: true, format: 'gif' },
  { id: 216, text: '/拍头', hasImage: true, format: 'gif' },
  { id: 217, text: '/扯一扯', hasImage: true, format: 'gif' },
  { id: 218, text: '/舔一舔', hasImage: true, format: 'gif' },
  { id: 219, text: '/蹭一蹭', hasImage: true, format: 'gif' },
  { id: 220, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 221, text: '/顶呱呱', hasImage: true, format: 'gif' },
  { id: 222, text: '/抱抱', hasImage: true, format: 'gif' },
  { id: 223, text: '/暴击', hasImage: true, format: 'gif' },
  { id: 224, text: '/开枪', hasImage: true, format: 'gif' },
  { id: 225, text: '/撩一撩', hasImage: true, format: 'gif' },
  { id: 226, text: '/拍桌', hasImage: true, format: 'gif' },
  { id: 227, text: '/拍手', hasImage: true, format: 'gif' },
  { id: 229, text: '/干杯', hasImage: true, format: 'gif' },
  { id: 230, text: '/嘲讽', hasImage: true, format: 'gif' },
  { id: 231, text: '/哼', hasImage: true, format: 'gif' },
  { id: 232, text: '/佛系', hasImage: true, format: 'gif' },
  { id: 233, text: '/掐一掐', hasImage: true, format: 'gif' },
  { id: 234, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 235, text: '/颤抖', hasImage: true, format: 'gif' },
  { id: 236, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 237, text: '/偷看', hasImage: true, format: 'gif' },
  { id: 238, text: '/扇脸', hasImage: true, format: 'gif' },
  { id: 239, text: '/原谅', hasImage: true, format: 'gif' },
  { id: 240, text: '/喷脸', hasImage: true, format: 'gif' },
  { id: 241, text: '/生日快乐', hasImage: true, format: 'gif' },
  { id: 242, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 243, text: '/甩头', hasImage: true, format: 'gif' },
  { id: 244, text: '/扔狗', hasImage: true, format: 'gif' },
  { id: 245, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 246, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 247, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 260, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 261, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 262, text: '/脑阔疼', hasImage: true, format: 'gif' },
  { id: 263, text: '/沧桑', hasImage: true, format: 'gif' },
  { id: 264, text: '/捂脸', hasImage: true, format: 'gif' },
  { id: 265, text: '/辣眼睛', hasImage: true, format: 'gif' },
  { id: 266, text: '/哦哟', hasImage: true, format: 'gif' },
  { id: 267, text: '/头秃', hasImage: true, format: 'gif' },
  { id: 268, text: '/问号脸', hasImage: true, format: 'gif' },
  { id: 269, text: '/暗中观察', hasImage: true, format: 'gif' },
  { id: 270, text: '/emm', hasImage: true, format: 'gif' },
  { id: 271, text: '/吃瓜', hasImage: true, format: 'gif' },
  { id: 272, text: '/呵呵哒', hasImage: true, format: 'gif' },
  { id: 273, text: '/我酸了', hasImage: true, format: 'gif' },
  { id: 274, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 277, text: '/汪汪', hasImage: true, format: 'gif' },
  { id: 278, text: '/汗', hasImage: true, format: 'gif' },
  { id: 279, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 280, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 281, text: '/无眼笑', hasImage: true, format: 'gif' },
  { id: 282, text: '/敬礼', hasImage: true, format: 'gif' },
  { id: 283, text: '/狂笑', hasImage: true, format: 'gif' },
  { id: 284, text: '/面无表情', hasImage: true, format: 'gif' },
  { id: 285, text: '/摸鱼', hasImage: true, format: 'gif' },
  { id: 286, text: '/魔鬼笑', hasImage: true, format: 'gif' },
  { id: 287, text: '/哦', hasImage: true, format: 'gif' },
  { id: 288, text: '/请', hasImage: true, format: 'gif' },
  { id: 289, text: '/睁眼', hasImage: true, format: 'gif' },
  { id: 290, text: '/敲开心', hasImage: true, format: 'gif' },
  { id: 291, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 292, text: '/让我康康', hasImage: true, format: 'gif' },
  { id: 293, text: '/摸锦鲤', hasImage: true, format: 'gif' },
  { id: 294, text: '/期待', hasImage: true, format: 'gif' },
  { id: 295, text: '/拿到红包', hasImage: true, format: 'gif' },
  { id: 296, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 297, text: '/拜谢', hasImage: true, format: 'gif' },
  { id: 298, text: '/元宝', hasImage: true, format: 'gif' },
  { id: 299, text: '/牛啊', hasImage: true, format: 'gif' },
  { id: 300, text: '/胖三斤', hasImage: true, format: 'gif' },
  { id: 301, text: '/好闪', hasImage: true, format: 'gif' },
  { id: 302, text: '/左拜年', hasImage: true, format: 'gif' },
  { id: 303, text: '/右拜年', hasImage: true, format: 'gif' },
  { id: 304, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 305, text: '/右亲亲', hasImage: true, format: 'gif' },
  { id: 306, text: '/牛气冲天', hasImage: true, format: 'gif' },
  { id: 307, text: '/喵喵', hasImage: true, format: 'gif' },
  { id: 308, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 309, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 310, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 311, text: '/打call', hasImage: true, format: 'gif', stickerId: '1', stickerType: 1 },
  { id: 312, text: '/变形', hasImage: true, format: 'gif', stickerId: '2', stickerType: 1 },
  { id: 313, text: '/__喜欢', hasImage: true, format: 'gif', stickerId: '2', stickerType: 1 },
  { id: 314, text: '/仔细分析', hasImage: true, format: 'gif', stickerId: '4', stickerType: 1 },
  { id: 315, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 316, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 317, text: '/菜汪', hasImage: true, format: 'gif', stickerId: '7', stickerType: 1 },
  { id: 318, text: '/崇拜', hasImage: true, format: 'gif', stickerId: '8', stickerType: 1 },
  { id: 319, text: '/比心', hasImage: true, format: 'gif', stickerId: '9', stickerType: 1 },
  { id: 320, text: '/庆祝', hasImage: true, format: 'gif', stickerId: '10', stickerType: 1 },
  { id: 321, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 322, text: '/拒绝', hasImage: true, format: 'gif' },
  { id: 323, text: '/嫌弃', hasImage: true, format: 'gif' },
  { id: 324, text: '/吃糖', hasImage: true, format: 'gif', stickerId: '12', stickerType: 1 },
  { id: 325, text: '/惊吓', hasImage: true, format: 'gif', stickerId: '14', stickerType: 1 },
  { id: 326, text: '/生气', hasImage: true, format: 'gif', stickerId: '15', stickerType: 1 },
  { id: 327, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 328, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 329, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 330, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 331, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 332, text: '/举牌牌', hasImage: true, format: 'gif' },
  { id: 333, text: '/烟花', hasImage: true, format: 'png', stickerId: '19', stickerType: 1 },
  { id: 334, text: '/虎虎生威', hasImage: true, format: 'png' },
  { id: 335, text: '/__绿马', hasImage: true, format: 'png' },
  { id: 336, text: '/豹富', hasImage: true, format: 'png' },
  { id: 337, text: '/花朵脸', hasImage: true, format: 'gif', stickerId: '22', stickerType: 1 },
  { id: 338, text: '/我想开了', hasImage: true, format: 'gif', stickerId: '20', stickerType: 1 },
  { id: 339, text: '/舔屏', hasImage: true, format: 'gif', stickerId: '21', stickerType: 1 },
  { id: 340, text: '/xxx', hasImage: true, format: 'gif' },
  { id: 341, text: '/打招呼', hasImage: true, format: 'gif', stickerId: '24', stickerType: 1 },
  { id: 342, text: '/酸Q', hasImage: true, format: 'gif', stickerId: '26', stickerType: 1 },
  { id: 343, text: '/我方了', hasImage: true, format: 'gif', stickerId: '27', stickerType: 1 },
  { id: 344, text: '/大怨种', hasImage: true, format: 'gif', stickerId: '28', stickerType: 1 },
  { id: 345, text: '/红包多多', hasImage: true, format: 'gif', stickerId: '29', stickerType: 1 },
  { id: 346, text: '/你真棒棒', hasImage: true, format: 'gif', stickerId: '25', stickerType: 1 },
  { id: 347, text: '/大展宏兔', hasImage: true, format: 'png' },
  { id: 348, text: '/福萝卜', hasImage: true, format: 'png' },
  { id: 349, text: '/坚强', hasImage: true, format: 'gif', stickerId: '32', stickerType: 1 },
  { id: 350, text: '/贴贴', hasImage: true, format: 'gif', stickerId: '31', stickerType: 1 },
  { id: 351, text: '/敲敲', hasImage: true, format: 'gif', stickerId: '30', stickerType: 1 },
  { id: 352, text: '/咦', hasImage: true, format: 'gif' },
  { id: 353, text: '/拜托', hasImage: true, format: 'gif' },
  { id: 354, text: '/尊嘟假嘟', hasImage: true, format: 'gif' },
  { id: 355, text: '/耶', hasImage: true, format: 'gif' },
  { id: 356, text: '/666', hasImage: true, format: 'gif' },
  { id: 357, text: '/裂开', hasImage: true, format: 'gif' },
  { id: 358, text: '/骰子', hasImage: true, format: 'gif', stickerId: '33', stickerType: 2 },
  { id: 359, text: '/包剪锤', hasImage: true, format: 'gif', stickerId: '34', stickerType: 2 },
  { id: 392, text: '/龙年快乐', hasImage: false, stickerId: '38', stickerType: 3 },
  { id: 393, text: '/新年中龙', hasImage: false, stickerId: '39', stickerType: 3 },
  { id: 394, text: '/新年大龙', hasImage: false, stickerId: '40', stickerType: 3 },
  { id: 395, text: '/略略略', hasImage: false, stickerId: '41', stickerType: 1 },
]
